
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

# Current configuration:
# - django 3.2, python 3.8, wagtail 4.1, postgres
# - django 4.1, python 3.8, wagtail 4.1, sqlite
# - django 3.2, python 3.8, wagtail 5.2, postgres
# - django 4.1, python 3.8, wagtail 5.2, sqlite
# - django 3.2, python 3.9, wagtail 4.1, postgres
# - django 4.1, python 3.9, wagtail 4.1, sqlite
# - django 3.2, python 3.9, wagtail 5.2, postgres
# - django 4.1, python 3.9, wagtail 5.2, sqlite
# - django 3.2, python 3.10, wagtail 4.1, postgres
# - django 4.1, python 3.10, wagtail 4.1, sqlite
# - django 3.2, python 3.10, wagtail 5.2, postgres
# - django 4.1, python 3.10, wagtail 5.2, sqlite
# - django 4.1, python 3.11, wagtail 4.1, sqlite
# - django 4.1, python 3.11, wagtail 5.2, sqlite
# - django 4.2, python 3.11, wagtail 5.2, sqlite
# - django 4.2, python 3.11, wagtail main, sqlite (allow failures)
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: "3.8"
            django: "Django>=3.2,<4.0"
            wagtail: "wagtail>=4.1,<4.2"
            database: "postgresql"
            experimental: false
          - python: "3.8"
            django: "Django>=4.1,<4.2"
            wagtail: "wagtail>=4.1,<4.2"
            database: "sqlite3"
            experimental: false
          - python: "3.8"
            django: "Django>=3.2,<4.0"
            wagtail: "wagtail>=5.2,<5.3"
            database: "postgresql"
            experimental: false
          - python: "3.8"
            django: "Django>=4.1,<4.2"
            wagtail: "wagtail>=5.2,<5.3"
            database: "sqlite3"
            experimental: false
          - python: "3.9"
            django: "Django>=3.2,<4.0"
            wagtail: "wagtail>=4.1,<4.2"
            database: "postgresql"
            experimental: false
          - python: "3.9"
            django: "Django>=4.1,<4.2"
            wagtail: "wagtail>=4.1,<4.2"
            database: "sqlite3"
            experimental: false
          - python: "3.9"
            django: "Django>=3.2,<4.0"
            wagtail: "wagtail>=5.2,<5.3"
            database: "postgresql"
            experimental: false
          - python: "3.9"
            django: "Django>=4.1,<4.2"
            wagtail: "wagtail>=5.2,<5.3"
            database: "sqlite3"
            experimental: false
          - python: "3.10"
            django: "Django>=3.2,<4.0"
            wagtail: "wagtail>=4.1,<4.2"
            database: "postgresql"
            experimental: false
          - python: "3.10"
            django: "Django>=4.1,<4.2"
            wagtail: "wagtail>=4.1,<4.2"
            database: "sqlite3"
            experimental: false
          - python: "3.10"
            django: "Django>=3.2,<4.0"
            wagtail: "wagtail>=5.2,<5.3"
            database: "postgresql"
            experimental: false
          - python: "3.10"
            django: "Django>=4.1,<4.2"
            wagtail: "wagtail>=5.2,<5.3"
            database: "sqlite3"
            experimental: false
          - python: "3.11"
            django: "Django>=4.1,<4.2"
            wagtail: "wagtail>=4.1,<4.2"
            database: "sqlite3"
            experimental: false
          - python: "3.11"
            django: "Django>=4.1,<4.2"
            wagtail: "wagtail>=5.2,<5.3"
            database: "sqlite3"
            experimental: false
          - python: "3.11"
            django: "Django>=4.2,<4.3"
            wagtail: "wagtail>=5.2,<5.3"
            database: "postgresql"
            experimental: false

          - python: "3.11"
            django: "Django>=4.2,<4.3"
            wagtail: "git+https://github.com/wagtail/wagtail.git@main#egg=wagtail"
            database: "sqlite3"
            experimental: true

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
